2020-08-19 08:54:36.121 +0530	START		Running RCA_Sched_Scalability_ConfirmAppointment.script
2020-08-19 08:54:36.602 +0530	Log		Using local data	6	on_rca_sched_scalability_dataloader	RCA_Sched_Scalability_DataLoader.script
2020-08-19 08:54:36.679 +0530	Log		((domain:"solm64", password:"cerner", rcaPath:@"C:\\Program Files\\Cerner\\RevenueCycle3.55.21\\RevenueCycle.exe", userName:"regauto"))	8	on_rca_sched_scalability_dataloader	RCA_Sched_Scalability_DataLoader.script
2020-08-19 08:54:37.148 +0530	Log		(domain:"solm64", password:"cerner", rcaPath:@"C:\\Program Files\\Cerner\\RevenueCycle3.55.21\\RevenueCycle.exe", userName:"regauto")	20	on_rca_sched_scalability_confirmappointment	RCA_Sched_Scalability_ConfirmAppointment.script
2020-08-19 08:54:37.201 +0530	Log		(appointmentName:"Recur_Data_Build", comment:"Test Comment", confirmedDate:"17-AUG-2020 08:00:00.00", confirmedTime:"", location:"RCA Reporting", locationGroup:"RegAuto Locations", patientName:"BASE, TEST123", rescheduleReason:"Patient Requested", resource:"Resource Group", resourceGroup:"Recur_Resource_Group1", testDate:"", timeFrame:"All Day")	21	on_rca_sched_scalability_confirmappointment	RCA_Sched_Scalability_ConfirmAppointment.script
2020-08-19 08:54:38.013 +0530	Exception		Remote Connection Unavailable	20	on_subrulesoftheroad	OpenApplication.script
2020-08-19 08:54:38.340 +0530	Exception		Remote Connection Unavailable	6	on_killapplications	KillApplications.script
2020-08-19 08:54:38.828 +0530	EndTestCase		(Duration:"2.68", Errors:"1", Exceptions:"2", StartTime:"2020-08-19 08:54:36 +0530", Successes:"0", TestCase:"RCA_Sched_Scalability_ConfirmAppointment.script", Warnings:"0")
2020-08-19 08:54:39.293 +0530	FAILURE		No Remote Connection typetext Error - Remote Connection Unavailable -- Execution Time 0:00:02 RCA_Sched_Scalability_ConfirmAppointment.script
